### ISSUE TITLE
项目运行不起来

### ISSUE THREAD

**Issue by kyiree** [chenxingxing6/cxx-graduation#5]
作者您好，本人最近在做相关设计，本人技术欠缺，发现您的项目运行不起来，不知道该如何配置，请问能麻烦您整理一个能运行的版本吗

**Comment by 521God** [comment]
你应该看一下你的哪一部分运行不起来，说一下，最好有截图。




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "chenxingxing6/cxx-graduation"                                                                                    <notifications@github.com&gt;;
发送时间:&nbsp;2021年1月13日(星期三) 下午2:10
收件人:&nbsp;"chenxingxing6/cxx-graduation"<cxx-graduation@noreply.github.com&gt;;
抄送:&nbsp;"Subscribed"<subscribed@noreply.github.com&gt;;
主题:&nbsp;[chenxingxing6/cxx-graduation] 项目运行不起来 (#5)





 
作者您好，本人最近在做相关设计，本人技术欠缺，发现您的项目运行不起来，不知道该如何配置，请问能麻烦您整理一个能运行的版本吗

**Comment by HappierLee** [comment]
运行起来了吗

**Comment by youziayouzi** [comment]
我可以直接当做我的毕业设计吗
