### ISSUE TITLE
这个仓库没有项目真正的源码，只有脚手架的代码吗？

### ISSUE THREAD

**Issue by Starix610** [chenxingxing6/cxx-graduation#6]
逛了一圈，发现只是个脚手架？😅
大佬是否可以把项目完整代码开源出来呢？挺不错的项目，想学习下

**Comment by Tandejian7** [comment]
> 逛了一圈，发现只是个脚手架？😅
> 大佬是否可以把项目完整代码开源出来呢？挺不错的项目，想学习下

https://github.com/Tandejian7/netdisk 
希望能帮到你
